import { Metadata } from "next";
import "@/assets/globals.css";
import Link from "next/link";
import { navItems } from "@/constants";

export const metadata: Metadata = {
  title: "Root title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="p-8">
          <nav className="space-x-2 flex items-center">
            {navItems.map((item) => (
              <Link key={item.label} className="text-blue-500 hover:underline" href={item.link}>
                {item.label}
              </Link>
            ))}
          </nav>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
