import { Metadata } from 'next';
import '@/assets/globals.css';
import Link from 'next/link';
import { navItems } from '@/constants';
import StoreProvider from '@/redux/StoreProvider';

export const metadata: Metadata = {
  title: 'Root title',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <StoreProvider>
          <div className='p-8'>
            <nav className='flex items-center space-x-2'>
              {navItems.map((item) => (
                <Link
                  key={item.label}
                  className='text-blue-500 hover:underline'
                  href={item.link}
                >
                  {item.label}
                </Link>
              ))}
            </nav>
            <main>{children}</main>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
