import { Metadata } from "next";
import "@/assets/globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Root title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="space-x-1">
          <Link className="text-blue-500 hover:underline" href="/">
            Home
          </Link>
          <Link className="text-blue-500 hover:underline" href="/users">
            Users
          </Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
